
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.62
distribution_type: module
version: 0.01
name: File-Find-Rule-Perl
author: Adam Kennedy <cpan@ali.as>
license: perl
build_requires: 
  Test::More: 0.47
  File::Spec: 0.82
requires: 
  File::Find::Rule: 0.20
  perl: 5.005
abstract: Common rules for searching for Perl things
