---
abstract: 'Common rules for searching for Perl things'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: File::Find::Rule::Perl
name: File-Find-Rule-Perl
no_index:
  directory:
    - inc
    - t
requires:
  File::Find::Rule: 0.20
  File::Spec: 0.82
  Params::Util: 0.38
  Parse::CPAN::Meta: 1.38
  perl: 5.00503
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/File-Find-Rule-Perl
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/File-Find-Rule-Perl
version: 1.09
